### PR TITLE
Feature/rfls 69 accordion pane

### PR DESCRIPTION
**Pull request by DavidHughes**

### CODE REVIEW

**Comment by DavidHughes** [comment]
Closing this for now, realising I'm a bit hasty, only the style has been completed but I need to check over the behaviour. Will re-open later on.

**Comment by DavidHughes** [comment]
Re-opening this as I've now added the JS functionality we want for this, complete with a no-js solution so that content is accessible even when JS fails to load for some reason.

**Comment by DavidHughes** [comment]
I feel that HoundCI's complaints about collapsible-fieldset.scss should be tackled separately from this pull request as we risk causing a regression. The only change this PR does with that file are renaming it as part of renaming the old 'Accordion' pattern to 'Collapsible Fieldset', as agreed with Dan & Simon.

**Comment by DavidHughes** [comment]
Regarding icon fonts vs SVGs I believe we should be using SVGs instead of moving over to icon fonts, on the assumption that we are OK with IE8 not supporting SVGs. 

Good reads: 
 - https://css-tricks.com/icon-fonts-vs-svg/ This is a good point-by-point comparison which seems to heavily favour SVGs with the only exception being browser support.
 - http://ianfeather.co.uk/ten-reasons-we-switched-from-an-icon-font-to-svg/ more about specific issues that using Icon Fonts can lead to and how using SVGs can deal with it.

**Comment by DavidHughes** [comment]
Pending a change to fix cases where the text will overlay the image on smaller devices, do not merge, a fix will be up shortly.

**Comment by DavidHughes** [comment]
Fix has been pushed, ready for further review :)

**Comment by heylookalive** [comment]
We need to sort out the hound :/

Also we're coming back to the icons... For now let's merge!

**Pull request merged**
